# This is a basic workflow to help you get started with Actions

name: Docs build and publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      # Runs a set of commands using the runners shell
      - name: Build
        shell: cmd
        run: |
          dotnet tool install docfx --global
          cd docs
          docfx metadata
          docfx build
          
      - name: Publish
        shell: pwsh
        env:
          FTP_DOC_HOST: ${{ secrets.FTP_DOC_HOST }}
          FTP_DOC_PASSWORD: ${{ secrets.FTP_DOC_PASSWORD }}
          FTP_DOC_USERNAME: ${{ secrets.FTP_DOC_USERNAME }}
        run: .\publish.ps1 $env:FTP_DOC_HOST $env:FTP_DOC_USERNAME $env:FTP_DOC_PASSWORD
